blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_view
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name='create'),
    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('<slug>/delete', delete_blog_view, name='delete')
]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from mixed.views import (home_screen_view)
from account.views import (display_account_users, registration_view, logout_view, login_view, account_view, )
from django.contrib.auth import views as auth_views
from src.blog.views import must_authenticate_view

urlpatterns = [
    # path('mixed/', mixed_home_view),
    # path('mixed2/', mixed_2),
    # path('questions/', show_questions),

    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('users/', display_account_users, name='users'),
    path('register', registration_view, name='register'),
    path('logout', logout_view, name='logout'),
    path('login', login_view, name='login'),
    path('account', account_view, name='account'),
    path('blog/', include('src.blog.urls', 'blog')),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),

    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/account/', include('account.api.urls', 'account_api')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset_change/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset_change/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_change/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_change'
                                                                               '/password_reset_form.html'),
         name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_change/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mixed/models.py
from django.db import models

# Create your models here.

PRIORITY = [('H', 'High'), ('M', 'Medium'), ('L', 'Low')]


class Questions(models.Model):
    title = models.CharField(max_length=100)
    question = models.TextField(max_length=500)
    priority = models.CharField(max_length=1, choices=PRIORITY)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'The Question'
        verbose_name_plural = 'All Questions'

mixed/views.py
from django.shortcuts import render
from mixed.models import Questions
from blog.models import BlogPost
from operator import attrgetter
from blog.views import get_blog_queryset
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

NO_OF_POSTS_PER_PAGE = 5
# Create your views here.


def home_screen_view(request):
    context = {}
    query = request.GET.get('q', '')
    context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)

    # Pagination
    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, NO_OF_POSTS_PER_PAGE)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(NO_OF_POSTS_PER_PAGE)
    except Paginator:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    context['blog_posts'] = blog_posts
    return render(request, 'mixed/home.html', context)


# def mixed_home_view(request):
#     print(request.headers)
#     return render(request, "mixed/home.html", {})
#
# def mixed_2(request):
#     context = {}
#     context['Developer_Name'] = "Aryan Chauhan"
#     demoItemList = ["item1", "item2", "item3", "item4"]
#     context['demoItemList'] = demoItemList
#     return render(request, "mixed/home2.html", context)
#
#
# def show_questions(request):
#     context = {}
#     questions = Questions.objects.all()
#     context['questions'] = questions
#     return render(request, 'mixed/show_questions.html', context)
#

mixed/templates/mixed/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	@media (max-width: 768px) {
		.right-column{
			margin-left: 0px;
		}
	}
	@media (min-width: 768px) {
		.right-column{
			margin-left: 20px;
		}
	}
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	.left-column{
		padding:0px;
	}
	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	.my_hr{
		  border: 10px solid grey;
		  border-radius: 5px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'AC logo.png' %}" width="72" height="72">
					<p class="lead">Hey guys, check out the amazing blogs on this website. If you too wanna write
						a blog for the world to see, register now and start writing. It's an amazing platform.Enlighten
						the world with your knowledge or share any of your experiences/adventures.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container mb-3">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
						<hr class="my_hr">
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-pos-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

<!--		Pagination-->
		{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
		</div>
		<!-- end blog feed -->

		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'write_right.png' %}" width="72" height="72">
					<p class="lead text-center">Hey guys, check out the amazing blogs this website.<br>If you too wanna write
					a blog for the world too see, register now and start writing. Enlighten the world with your knowledge
					or share any of your experiences/adventures.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>

		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}

mixed/templates/mixed/home2.html
{% extends 'base.html' %}

{% block content %}

<div style = "border: 2px solid #000;">
    <h1>This is the body of the mixed app homepage</h1>
    <p>Here u write the stuff to be used in this page</p>
</div>

<br>Developer Name = {{Developer_Name}}<br>


<p><h3>Hey man, we are now using the snippets here : </h3> </p>

{% for item in demoItemList %}
    {% include 'mixed/snippets/home_snippets2.html' with value=item %}<br>
{% endfor %}

<p><h3> Here the snippet is finishing </h3></p>


{% endblock content %}

mixed/templates/mixed/home_save.html
{% extends 'base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Let's Build <br> No growing without building.</h1>
  <p class="lead">
      Hello, My name is Aryan Chauhan. I am an Android and Web developer. I love to make my ideas come alive in form of
      Apps and websites. This is my little space in this widespread web, where I present the apps I have created and the
      awesome projects that I work on. Check out my projects here and keep building and growing.
  </p>
</div>

{% endblock content %}

mixed/templates/mixed/show_questions.html
{% extends 'base.html' %}

{% block content %}

<div style="border: 1px solid #000; margin-left:5px">
    {% for question in questions %}
        {% include 'mixed/snippets/question_snippet.html' with value=question %}
    {% endfor %}
</div>

{% endblock content%}